# What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# Numpy Arrays Vs Python Sequences
- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a= np.array([1,2,3])
print(a) # call it a vector 1D
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2D and 3D
b = np.array([[1,3,4],[3,4,5]])
print(b) # call it a matrix 2D

a = np.array([[[1,2],[3,4]],[[2,3],[4,5]]])
print(a) # call it a tensor 3d

[[1 3 4]
 [3 4 5]]
[[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]]


In [4]:
#dtype
# change any datatype in numpy
np.array([1,2,3],dtype=complex)
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [6]:
# with reshape
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.random.random((3,4))

array([[0.71511789, 0.90602832, 0.33635929, 0.59403937],
       [0.79810293, 0.00262696, 0.97920023, 0.16127868],
       [0.23747446, 0.15099103, 0.11090665, 0.53514307]])

In [10]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [61]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
# ndim
a3.ndim

3

In [63]:
# shape
a3.shape

(2, 2, 2)

In [64]:
# size
a3.size

8

In [65]:
#itemsize
a3.itemsize

4

In [66]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype

In [67]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Array Operation

In [68]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
# scalar operation -> 1 number

# arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [73]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [76]:
# vector operation
# arthimetic
a2 + a1 # shape needs to be same

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Function

In [263]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[99., 75., 64.],
       [94., 92., 42.],
       [21., 88., 49.]])

In [264]:
# max/min/sum/prod
# 0 -> col 1 -> row
np.prod(a1,axis=1)

array([475200., 363216.,  90552.])

In [265]:
# mean/median/std/var
np.mean(a1,axis=1)

array([79.33333333, 76.        , 52.66666667])

In [92]:
# trignometry function
np.sin(a2)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [98]:
# dot product
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [101]:
# log and exponents
np.log(a1)
np.exp(a1)

C:\Users\Aniket\AppData\Local\Temp\ipykernel_7340\1488485187.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [107]:
# round/floor/ceil
a = np.random.random((2,3))*100
a

array([[77.50718205, 89.92881045, 26.49735567],
       [73.30679966, 80.06175883, 73.9399413 ]])

In [110]:
# print(np.round(a))
# print(np.ceil(a))
print(np.floor(a))

[[77. 89. 26.]
 [73. 80. 73.]]


# Indexing and Slicing

In [177]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [117]:
# indexing
a1[-1]

9

In [121]:
a2[1,2]

6

In [128]:
a3[1,1,0]

6

In [131]:
# Slicing
a1[2:5]

array([2, 3, 4])

In [165]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [178]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [195]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [199]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [201]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [202]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [203]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [210]:
# reshape
# all are temporary not permanent changes
# if results are shown immediately those are temp else it's permanent
print(a1)
a1.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [212]:
# transpose
print(a2)
np.transpose(a2)
a2.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [215]:
# ravel
# convert any ndim of array into 1D array (flatten)
print(a3)
a3.ravel()

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking
Use case: To connect multiple data from different sources Like innerjoin from sql

In [237]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [240]:
# Horizontal Stacking
np.hstack((a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [234]:
# Vertical Stacking
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [230]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [231]:
# Horizontal split
# it is not horizontal split but imagine as vertical split
np.hsplit(a1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [235]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [243]:
# Vertical split
# it is not horizontal split but imagine as vertical split
np.vsplit(a5,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [249]:
arr=(12,34,40,7,1,0)
a = np.array(arr)
a

array([12, 34, 40,  7,  1,  0])

In [262]:
a[:2]

array([12, 34])