**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [20]:
#Code here
a = np.zeros(11)
l = []
for i,j in enumerate(a):
    if i==5:
        j = 1
    l.append(j)
a = np.array(l)
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
#Code here
r = int(input('Enter row:'))
c = int(input('Enter col:'))
arr = np.random.random((r,c))
print(arr)
print('Avergage: ',np.mean(arr))

Enter row:3
Enter col:4
[[0.60497208 0.18394773 0.62376272 0.92817108]
 [0.77388343 0.40703651 0.28137006 0.81156591]
 [0.27001298 0.91966301 0.93264761 0.50697588]]
Avergage:  0.603667416123081


In [6]:
a,b = map(int, input('Enter two Numbers: ').split())
x = np.random.random((a,b))
print(x)
print('Avergage: ',arr.mean())

Enter two Numbers: 2 5
[[0.19222843 0.09045916 0.121929   0.16125776 0.71576397]
 [0.79628564 0.688607   0.95783363 0.0326616  0.92444251]]
Avergage:  0.603667416123081


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [38]:
#Code here
def array(a,b):
    arr = np.ones((a,b))
    arr[1:a-1,1:b-1] = 0
    return arr

array(6,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
def borderArray(a,b):
    a = np.ones((a,b))
    a[1:-1,1:-1] = 0
    return a
borderArray(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [40]:
#Code here
np.random.random(10)

array([0.17555344, 0.45073358, 0.81041425, 0.20502104, 0.82227676,
       0.46897778, 0.95024394, 0.6779936 , 0.32324981, 0.16380027])

In [14]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [437]:
#Code here
print('No')

No


In [16]:
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [59]:
#Code here
a = np.random.random((5,5))
a = np.round(a*4)
a

array([[3., 3., 3., 1., 0.],
       [3., 1., 2., 3., 3.],
       [3., 3., 1., 3., 3.],
       [3., 1., 3., 0., 2.],
       [3., 1., 4., 3., 3.]])

In [27]:
z = np.zeros((5,5))
a = np.arange(5)
print(a)
print(z)
z = z + a
print(z)

[0 1 2 3 4]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [57]:
#code here
point = np.array([2,3])
cord = np.random.randint(0,100,(10,2))
print(cord)
np.sqrt(np.sum((cord -point)**2,axis=1)).astype('int')

[[60 77]
 [30  4]
 [68  5]
 [84 74]
 [56 11]
 [69  8]
 [72 88]
 [37 68]
 [25 10]
 [21 62]]


array([ 94,  28,  66, 108,  54,  67, 110,  73,  24,  61])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [59]:
#Code here
a = np.random.randint(1,337,(6,7,8))
a

array([[[277, 330, 154, 101, 273, 208,  58, 271],
        [ 44,  79,  40, 289, 189, 302, 280, 262],
        [326, 217,  63, 182, 292, 188, 261, 200],
        [171, 152, 325,  98, 188,   3, 179, 142],
        [142, 164,  65,  26,  69,  72, 207, 100],
        [ 35, 299, 316,  86, 174,  70,  55, 293],
        [ 46,  10, 220, 120, 206, 133, 199,  55]],

       [[ 58, 289,   9, 107, 251, 124,  28,  33],
        [123, 260, 122,  76,  52, 259, 333, 153],
        [  4, 284, 235, 174, 152, 329,   5, 192],
        [251,  76,  22, 177, 181,  53, 257, 254],
        [175, 255, 190, 268, 323, 102,  65,  83],
        [248,  43, 257,  40, 321,  33, 265, 126],
        [178, 309, 243, 110, 246, 103, 141, 286]],

       [[ 10, 290, 248, 234, 280, 137,  59, 105],
        [120, 249, 260, 249, 137, 295, 189,  83],
        [ 22, 109, 111, 153, 275,  27, 191,  53],
        [  6, 135,  52, 276, 281,  94, 252, 123],
        [248,   5,  17,  68, 158, 102,  81, 190],
        [198,  61, 265,  44,   2, 145, 245, 32

In [60]:
for i,j in enumerate(np.nditer(a)):
    if i==100:
        print(j)

321


In [63]:
a[np.unravel_index(100,(6,7,8))]

321

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [441]:
#Code here
a = [1 ,2 ,3 ,4 ,-8 ,-10]
arr = np.array(a)

print(arr[::-1].astype(float))

[-10.  -8.   4.   3.   2.   1.]


In [67]:
a = input().strip().split()
np.array(a[::-1],dtype = np.float32)

3 4 5 2 22 5 5


array([ 5.,  5., 22.,  2.,  5.,  4.,  3.], dtype=float32)

#### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [68]:
#Code here
a = np.array([1,2])
print('elements_count :',len(a))
print('elements_count :',a.size)

elements_count : 2
elements_count : 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [85]:
#Code here
arr1 = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
arr2 = np.array([33.17344305, 45.61961654, 82.05405781 ,80.9647098,  68.82830233, 91.52064278])
arr3 = np.array([[33.17344305, 45.61961654, 82.05405781] ,[80.9647098,  68.82830233, 91.52064278]])
l = [1,2,3,4]

def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy array")
    elif arr.ndim > 1:
        raise TypeError("Can't allow more than 1D array")
    else:
        num = np.exp(arr) 
        den = np.sum(num)
        print(num/den)
try:
    softmax(arr3)
except Exception as e:
    print(e)

Can't allow more than 1D array


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [87]:
#Coder here
a= np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])

def vertical(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Only Numpy datatype is allowed")
        
    return np.vstack(args) 

a = np.array(a)
b = np.array(b)
try:
    print(vertical(a,b))
except TypeError as e:
    print(e)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [446]:
#Code here
import datetime as dt
def date(start = '', end = ''):
    l = []
    if type(start) != str and type(end) != str:
        raise TypeError('Only String datatype allowed')
    else:
        start = dt.datetime.strptime(start,'%Y-%m-%d')
        end = dt.datetime.strptime(end,'%Y-%m-%d')
    
    delta = end - start
    for i in range(delta.days + 1):
        next_day = start + dt.timedelta(days = i)
        l.append(str(next_day).split()[0])
    return np.array(l)

try:
    print(date(start = '2020-09-15', end = '2020-09-25'))
except TypeError as e:
    print(e)

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


In [93]:
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError
        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1
    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end 
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [94]:
#code here
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [448]:
mean = np.mean(arr,axis = 1)
print(mean)

x = np.empty(shape=[0,len(mean)])
for i in range(len(arr)):
    sub = np.array(arr[i] - mean[i])
    x = np.append(x,[sub],axis=0)
    
x

[1. 4. 7.]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [99]:
mean = arr.mean(axis=1,keepdims = True)
arr - mean

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [100]:
#Code here
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [450]:
temp = arr[:,1].copy()
arr[:,1] = arr[:,0]
arr[:,0] = temp
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [101]:
arr[:, [0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [110]:
#Code here
arr = np.arange(1,11)
for i in arr:
    if i%2 != 0:
        arr[i] = -1
arr

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1])

In [113]:
arr = np.arange(1,10)

arr[arr % 2 == 1] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [114]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

In [453]:
l = []
for i,j in zip(a,b):
    if i>j:
        l.append(i)
    else:
        l.append(j)
l

[6, 3, 1, 7, 8]

In [121]:
a[b > a] = b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [124]:
# Given
arr=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr

array([[5801, 5812,  367, 7932, 5956],
       [4482, 3421, 3430, 2555, 1258],
       [8427, 3743, 2482, 7760, 5204],
       [ 572,  851, 8179, 9648, 1421],
       [7148, 8766, 4195, 6305, 5443],
       [5941, 2537, 5598, 2286, 1690],
       [3255, 1182, 5142, 9852, 5361],
       [2047, 7833, 4717, 9408, 1691]])

In [125]:
#Code here
arr = arr[:,::2]
arr

array([[5801,  367, 5956],
       [4482, 3430, 1258],
       [8427, 2482, 5204],
       [ 572, 8179, 1421],
       [7148, 4195, 5443],
       [5941, 5598, 1690],
       [3255, 5142, 5361],
       [2047, 4717, 1691]])

In [465]:
min_ = np.min(arr)
max_ = np.max(arr)
shape = arr.shape
l = []

for i in arr.ravel():
    l.append(i-min_/max_ - min_)
a = np.array(l).reshape(shape)
a

array([[ 7.74296189e+03,  5.89996189e+03,  6.24961887e+02],
       [ 6.59996189e+03,  5.80996189e+03,  4.69596189e+03],
       [ 7.38596189e+03,  5.44961887e+02, -3.81125227e-02],
       [ 8.10961887e+02,  5.38896189e+03,  2.55196189e+03],
       [ 2.96188748e+00,  9.75961887e+02,  7.61496189e+03],
       [ 8.88961887e+02,  6.75196189e+03,  1.33961887e+02],
       [ 4.95896189e+03,  1.23596189e+03,  9.53996189e+03],
       [ 6.18096189e+03,  8.54796189e+03,  2.55696189e+03]])

In [126]:
((arr - arr.min())/(arr.max() - arr.min()))

array([[0.67419355, 0.        , 0.69342432],
       [0.51054591, 0.38002481, 0.11054591],
       [1.        , 0.26240695, 0.60012407],
       [0.02543424, 0.96923077, 0.13076923],
       [0.84131514, 0.47493797, 0.62977667],
       [0.69156328, 0.64900744, 0.16414392],
       [0.35831266, 0.59243176, 0.61960298],
       [0.20843672, 0.53970223, 0.16426799]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [139]:
#Code here
arr=np.array([12,34,40,7,1,0])

def nth_largest(arr,n):
    if n > len(arr):
        raise IndexError('N is out of index')
    return sorted(arr,reverse=True)[n-1]

nth_largest(arr,3)

12

In [141]:
arr=np.array([12,34,40,7,1,0])

def nth_largest(arr,n):
    if n > len(arr):
        raise IndexError('N is out of index')
    arr.sort()
    return arr[-n]

nth_largest(arr,1)

40

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [144]:
#code here
a = np.array([1,2,3])

In [150]:
rep = np.repeat(a,repeats=3,axis=0)
tile = np.tile(a,3)

In [151]:
# 1st way
np.append(rep,tile)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [152]:
#2nd way
np.hstack((rep,tile))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])